[package]
name = "axum-session-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
axum-core = "0.4.3"
axum-extra = { version = "0.9.3", features = ["cookie"] }
futures = "0.3.30"
tower = "0.4.13"